### ISSUE TITLE
安装后，无法正常访问（访问会白屏）

### ISSUE THREAD

**Issue by linjialaowang** [BobCoderS9/Bob-Theme-Argon#1]
系统环境：Debian10 aapenal 使用v2board 推荐配置
安装后，启用主题，文件权限改为www递归755。
访问网站用户页面会白屏。由于没有设备，希望大佬能帮忙看看。

**Comment by BobCoderS9** [comment]
下载到theme目录过后要修改当前文件夹名为bob-argon，然后在后台选择主题bob-argon就行了
