### ISSUE TITLE
流量显示问题（作者大大务必认真看）

### ISSUE THREAD

**Issue by 1665169869** [BobCoderS9/Bob-Theme-Argon#10]
如图说明，根据接口u是已用上行 d是已用下行，这个真的不是主题的js的bug吗？
因为根据原生主题的话显示的是下行 更换bob主题后变成显示上行
![image](https://user-images.githubusercontent.com/50762038/127741156-6fc74ae1-62cc-4de8-a69d-a2bb7630cd05.png)

**Comment by 1665169869** [comment]
根据主题的**app.eea12aea.js**文件 我找到了**t.sub.u**这个变量，这个应该是调用了json的，改成了**t.sub.d**就显示成下行了

**Comment by BobCoderS9** [comment]
暂未发现问题。

![](https://shige.group/such/pic.php/forum/pic/item/a8014c086e061d95e25a238f6cf40ad162d9ca6d/mlike.jpg)


![](https://shige.group/such/pic.php/forum/pic/item/9213b07eca8065383cf2b0a480dda144ad348268/mlike.jpg)

![](https://shige.group/such/pic.php/forum/pic/item/e7cd7b899e510fb3a1096320ce33c895d1430c70/mlike.jpg)

**Comment by 1665169869** [comment]
我是说这个：
流量显示问题，这是我修改了过后前两张图显示成了下行流量，如果未修改就显示上行流量（如图三）
![image](https://user-images.githubusercontent.com/50762038/127741892-2d95d172-e7eb-4e1f-bde7-552e27ad9f1d.png)
![image](https://user-images.githubusercontent.com/50762038/127741896-8ab6684a-4826-4667-8aa0-f009f849ba2d.png)
![$7DY) )Y{NZXS HZ(XF75ML](https://user-images.githubusercontent.com/50762038/127741916-1fc2d980-f327-4df1-8f50-72e48e0038d1.png)

**Comment by 1665169869** [comment]
![image](https://user-images.githubusercontent.com/50762038/127741968-6380fa3d-7b3b-4981-b810-c215385d7232.png)
![image](https://user-images.githubusercontent.com/50762038/127741973-f8f9c911-f23e-4fa2-b882-994322a46236.png)
并且我发现上面的流量进度条是不会动的，一直保持0%

**Comment by 1665169869** [comment]
虽然不知道作者大大之前考虑的是只显示上行还是什么，但根据v2b的流量计算 应该是上行+下行
也就是说写法应该是：t.sub.u + t.sub.d = 使用流量

**Comment by BobCoderS9** [comment]
已修复
