### ISSUE TITLE
忘记密码按钮bug

### ISSUE THREAD

**Issue by Return-s** [BobCoderS9/Bob-Theme-Argon#13]
1.从登录界面点击忘记密码，无法进入，必须从注册页面才能进入
![2](https://user-images.githubusercontent.com/78198618/127757501-424c69dd-4e4e-4785-a50a-c6b6e406aa6c.png)
2.忘记密码页面下方字体不居中
![1](https://user-images.githubusercontent.com/78198618/127757545-9c2c2efb-e0ce-4fd6-8d5e-fe3e4d4b01f3.png)

**Comment by BobCoderS9** [comment]
已修复
