### ISSUE TITLE
节点列表-节点状态，国旗显示从汉字 “地区”识别改为emoji的建议

### ISSUE THREAD

**Issue by pudding1111** [BobCoderS9/Bob-Theme-Argon#15]
你好，开发者。
在v2b后台节点名称上，一般的设置为“ 🇺🇸 US02 4837 500m”的名称，其中，“🇺🇸”为emoji,这样的好处是在clash v2rayng 小火箭等能显示国旗的客户端，都会有如图的结果。
![image](https://user-images.githubusercontent.com/56715156/127761577-217dab6a-ed00-4b10-8d2a-6009aeb235ac.png)
可是这样的设置在该主题下并不能很好的显示国旗
![image](https://user-images.githubusercontent.com/56715156/127761597-e4caeacd-f4ca-4495-8d14-4fc5c715320f.png)

该主题的只有在名称为 【地区】-xx  的情况下才能正确显示国旗
![image](https://user-images.githubusercontent.com/56715156/127761617-3fc5ee03-b162-414e-a209-e6e7710599db.png)
在clash v2rayng 小火箭的客户端会有如下显示
![image](https://user-images.githubusercontent.com/56715156/127761529-337b3dd8-2547-4b41-9648-a863d3de8280.png)
因此，我建议将该主题的国旗识别从 中文【地区】 改为 emoji

**Comment by BobCoderS9** [comment]
已修复
