### ISSUE TITLE
重置当月流量订单 页面无法滑动

### ISSUE THREAD

**Issue by pengchujin** [BobCoderS9/Bob-Theme-Argon#21]
![截屏2021-08-01 下午7.44.11.jpg](https://i.loli.net/2021/08/01/2vZVmhaTrlJezR7.jpg)
无法滑动选择支付。

**Comment by BobCoderS9** [comment]
什么叫滑动选择支付

**Comment by pengchujin** [comment]
支付按钮在这页面的下面，没法往下滑动页面选择。

**Comment by BobCoderS9** [comment]
私聊我，发我地址看下，我没碰到

**Comment by BobCoderS9** [comment]
已修复
