### ISSUE TITLE
【高危】验证码问题

### ISSUE THREAD

**Issue by 1665169869** [BobCoderS9/Bob-Theme-Argon#22]
注册用户里少了个验证码的input标签
忘记密码里点击获取验证码后不会弹出谷歌人机验证
![image](https://user-images.githubusercontent.com/50762038/127774057-53e563c2-4b20-4794-a672-035fa755d38a.png)
![image](https://user-images.githubusercontent.com/50762038/127774060-825603ed-f71f-412c-ad9b-8ba0321fab63.png)

**Comment by BobCoderS9** [comment]
已修复
