### ISSUE TITLE
订单页面问题

### ISSUE THREAD

**Issue by 1665169869** [BobCoderS9/Bob-Theme-Argon#23]
图一是原版主题，可以查看已折扣订单，图二是bob主题，无法查看已折扣订单
还有一个就是图三在1980x1080的分辨率情况下在1194x813的分辨率的情况下（图四）
图三查看详情不是一行排列 只有图四是一行排列
而且图四会出现【操作】会出现置顶效果
![image](https://user-images.githubusercontent.com/50762038/127774294-4f949870-7356-4b0e-820b-2440ff310745.png)
![image](https://user-images.githubusercontent.com/50762038/127774383-d7629f9e-4860-4e5f-9e10-a098182a75ee.png)
![image](https://user-images.githubusercontent.com/50762038/127774415-85f6bde4-89f5-432d-986b-2462a6735a81.png)
![image](https://user-images.githubusercontent.com/50762038/127774460-49da79e6-035a-4e26-ad31-ce5dde36df80.png)

**Comment by BobCoderS9** [comment]
已修复
