### ISSUE TITLE
部分问题反馈 1.头像 2.wap 自适应 3.自定义订阅显示

### ISSUE THREAD

**Issue by ZHQSM** [BobCoderS9/Bob-Theme-Argon#29]
1.头像不用代理显示不正常  https://gravatar.cat.net/avatar/ 
2. 手机 点订单页显示不正常  侧边栏点击后 只能点x关闭  选择选项不会自己关闭
3. 建议增加只显示需要的订阅选项 不需要的订阅 可以设置关闭 全部显示对新手不友好。

**Comment by 1665169869** [comment]
第三点也不是主题问题啊，后端不是可以设置？

**Comment by BobCoderS9** [comment]
头像不归主题管，自己去看改后台

**Comment by 1665169869** [comment]
头像的问题可以在这个文件里的**info**函数即可修改，改下其他cdn就行

> /www/wwwroot/网站目录/app/Http/Controllers/User/UserController.php

**Comment by 1665169869** [comment]
> 头像不归主题管，自己去看改后台

不过手机订单页雀氏有点问题，创建日期会看不到
