### ISSUE TITLE
发现比较影响的bug

### ISSUE THREAD

**Issue by 1665169869** [BobCoderS9/Bob-Theme-Argon#33]
bug复现过程：
登录账号后，选登录账号，再点击【忘记密码?】或【注册账号】将会返回到https://xxxxxx/#/login
根据抓包来看，反悔了这样的结果，并且会一直请求check
![image](https://user-images.githubusercontent.com/50762038/129199941-8be8704a-b684-4578-87e9-9f786bf6f35b.png)

**Comment by BobCoderS9** [comment]
没懂什么意思

**Comment by 1665169869** [comment]
> 没懂什么意思

不知道现在修复了没，就是如果登录账号后，退出登录再点击忘记密码或注册账号会返回到用户登陆这个页面

**Comment by BobCoderS9** [comment]
暂未发现这个问题，你可以去demo站里面测试下在反馈
