### ISSUE TITLE
关于移动端（手机）登录前端后菜单不受控制弹出遮挡页面的问题

### ISSUE THREAD

**Issue by lankerens** [BobCoderS9/Bob-Theme-Argon#34]
### 先放图片

![image](https://user-images.githubusercontent.com/49162373/129219472-a3f2ed86-70c9-4a09-a24c-0da29d74ae44.png)

![image](https://user-images.githubusercontent.com/49162373/129219583-dd7b7d3c-1d3f-4321-a437-a08e2f091e59.png)

![image](https://user-images.githubusercontent.com/49162373/129219140-1a29cfc7-63bc-4fff-9413-fac69b5625dd.png)

<br>

<br>

### <font color="red">现在的情况是 我们没有点A区域， 点B、C 区域菜单却弹出来了</font>

<br>

<br>

---------------------------

另提一下， 因为注册页面的时候有那个 服务条款 是否打勾的选项， 好像不打勾，也能注册。。。。

**Comment by BobCoderS9** [comment]
已修复
