### ISSUE TITLE
美观问题，用户体验问题

### ISSUE THREAD

**Issue by MengleBoot** [BobCoderS9/Bob-Theme-Argon#35]
![D1BA3854-2298-4295-967A-1FAE08A0B4D8](https://user-images.githubusercontent.com/60128804/129397438-9c2daf5a-ed5a-4d82-98e1-8ab582a15448.png)
这个可以居中嘛🤣

![11D266CB-519F-4E48-8EC0-07591DD38B11](https://user-images.githubusercontent.com/60128804/129397543-654bbcff-f3cd-4e28-af42-615045ff87b0.png)
点击教程的时候会弹出菜单，还有好多地方都会

**Comment by BobCoderS9** [comment]
已修复
