### ISSUE TITLE
并没有兼容 StripeCreditCard 支付呢

### ISSUE THREAD

**Issue by Han-MeiM** [BobCoderS9/Bob-Theme-Argon#37]
如题，使用该主题后无法正确使用 Stripe CreditCard 进行支付，alipay 和 wechat 暂时还不清楚是否能使用。
我看了下，应该是没有调用获取 stripe pk 配置的接口，导致 stripe 无法初始化
详见 `user/comm/config` 接口

**Comment by BobCoderS9** [comment]
没有测试账号测试不了，方便的话联系我测试下 @BobS9

**Comment by Han-MeiM** [comment]
> 没有测试账号测试不了，方便的话联系我测试下 @BobS9

已联系你 tg
