### ISSUE TITLE
文档默认是 MarkDown，不支持 html 按钮。

### ISSUE THREAD

**Issue by pengchujin** [BobCoderS9/Bob-Theme-Argon#4]
默认的 markdown 会导致复制和链接按钮失效。

**Comment by BobCoderS9** [comment]
没懂你的意思，麻烦描述详细点，我对v2board不是太了解

**Comment by pengchujin** [comment]
![截屏2021-07-30 下午4.12.44.jpg](https://i.loli.net/2021/07/30/z8vne2DUI4MgwyC.jpg)

html 格式的文档按钮（复制或是导入链接都会失效）

**Comment by pudding1111** [comment]
确实会导致按钮失效,在知识库设置的代码如下:

<div class="card" style="width:98%">
  <img class="card-img-top" src="https://img.paulzzh.tech/touhou/random" alt="Card image cap">
  <div class="card-body">
    <h2 class="card-title">通用订阅链接</h2>
    <p class="card-text"><h4>{{subscribeUrl}}</h4></p>
    <h4><a class="btn btn-hero-primary" href="#/knowledge" onclick="copy('{{subscribeUrl}}')" ><i class="fa fa-share mr-1"></i> 单击复制上方订阅地址</a>
</h4>
  </div>

按照逻辑,点击时会将订阅复制到剪贴板上,但是实际上在该主题下,按钮功能并未生效.

还有一个问题,在仪表盘的 我的订阅 项目,根据v2b作者的文档显示  https://docs.v2board.com/use/node.html    ,共有11中参数,但是老哥的面板只取了相对常用的参数.

**Comment by BobCoderS9** [comment]
已修复
