### ISSUE TITLE
仪表盘加载大概率出错，求助

### ISSUE THREAD

**Issue by he514434** [BobCoderS9/Bob-Theme-Argon#49]
不知道什么原因，首页数据经常读区不到，会出现一直在加载的状况，并且会有报错，而且不是小概率事件，求助，感谢
<img width="1430" alt="321" src="https://user-images.githubusercontent.com/38560141/145448741-53f74f91-b06b-449e-afec-c3b158e258d6.png">

**Comment by BobCoderS9** [comment]
@he514434 前端主题又不会影响你的数据的，你这个明显是后端接口请求问题

**Comment by he514434** [comment]
连通vps重装以后，还是出现相同问题，aa6.0,contos7 php7.3 nginx1.17 mysql5.6,
v2board 和argon都是1.5.3的版本
还是出现相同问题

**Comment by he514434** [comment]
master版本存在此问题，直接下载1.5.3zip包则不会出现

**Comment by aiastia** [comment]
我也这个样
