### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by he514434** [BobCoderS9/Bob-Theme-Argon#50]
忘记密码页面，没有发送验证码，没有输入验证码
![image](https://user-images.githubusercontent.com/38560141/146665366-bcdf4ed3-c68c-4b5c-8560-966a1e5448ef.png)
首页重置订阅无效 重置当月流量无效
![image](https://user-images.githubusercontent.com/38560141/146665414-8b7a3a5f-69f9-42b6-b178-f9aa00bef1e2.png)
v2b版本1.5.3，argon版本1.5.3，1.5.4

**Comment by BobCoderS9** [comment]
自己检查配置，测试站并没有问题
Demo站：https://v2board.bobv.me/
测试账号：test@qq.com
测试密码：12345678
![image](https://user-images.githubusercontent.com/70191444/146665536-b2697b48-39a6-45ee-8467-26a57af4e11f.png)
![image](https://user-images.githubusercontent.com/70191444/146665546-cb43484c-070e-4f02-bfdb-883ac3759545.png)

**Comment by he514434** [comment]
测试站用的v2b是什么版本可以问一下吗，还有出了改主题，还需要更改别的吗
