### ISSUE TITLE
订阅链接里之好多客户端的订阅链接不见了

### ISSUE THREAD

**Issue by aspbyxx** [BobCoderS9/Bob-Theme-Argon#51]
如图![TRNU`)VS{(OX6} QYZ_%J1L](https://user-images.githubusercontent.com/34793812/147299164-d03e8eb9-660c-41de-b24d-85ddd99ba909.png)

**Comment by aspbyxx** [comment]
升了v1.5.4 测试版后好几个按钮不见了

**Comment by BobCoderS9** [comment]
自己去`dashboard.blade.php` 文件里面配置

**Comment by Cd1s** [comment]
oneclick客户端好像没有
