### ISSUE TITLE
1.54主题提示 套餐周期不能为空

### ISSUE THREAD

**Issue by edisnat** [BobCoderS9/Bob-Theme-Argon#52]
昨天刚换新主题 购买订阅套餐 提示 套餐周期不能为空，不能购买。换回官方主题就正常。

**Comment by aspbyxx** [comment]
我的也是 之前可以今天莫名奇妙不可以用了
![image](https://user-images.githubusercontent.com/34793812/147821184-39f1845d-d2a0-45ac-8365-757c80b6c6a8.png)

**Comment by aspbyxx** [comment]
我的也是之前可以正常订阅从昨晚开始出现这个问题
![image](https://user-images.githubusercontent.com/34793812/147821489-1ada7401-f325-4016-9579-a1b0bd9365b9.png)

**Comment by BobCoderS9** [comment]
测试服并没有问题。

**Comment by wdm1732418365** [comment]
同样遇到该问题
