### ISSUE TITLE
一些经常复现的问题（bug）

### ISSUE THREAD

**Issue by GZ1903** [BobCoderS9/Bob-Theme-Argon#57]
根据目前这个版本（1.5.4），一些经常出现的问题，希望得到Bob的回复。
1.登录进入主页-->仪表盘-->重置当月流量 or 重置订阅信息这两个摁键是无效的。
2.注册账号的时候，不管点不点击同意条款都可以注册，显得该摁键是个摆设一样。（切换原v2board并无此问题）
3.添加了注册的时候谷歌机器人认证后，使用该主题是不能够正常注册的。信息填写正确，认证通过，页面将会卡死。
建议作者把登录页面写成百分百显示，手机端或者小屏幕笔记本需要滑动一下才能很好的填写信息，不怎么人性化。。。。。

**Comment by BobCoderS9** [comment]
@GZ1903 问题一和问题三在demo站测试没有问题，检查你自己是不是最新版。问题二那个选项本来做的就是可选可不选，至于登录页本来就是自适应，哪里需要什么滑动

**Comment by GZ1903** [comment]
![DM_)6~R5~{53U@_JO7~X_IT](https://user-images.githubusercontent.com/55527553/149727022-3df975dc-0ebd-4890-8e8b-b02b8bf90410.png)
我再次进行新的部署（1.5.4和1.5.5两者均有测试）也是同样的结果，在仪表盘点击而不是节点列表。如图。
![8)P` {4015)DWU MC15HJNJ](https://user-images.githubusercontent.com/55527553/149728185-2aa92f7e-7328-48fe-aab9-e590b0257255.png)
至于问题2，其实不选应该禁止注册才对，原v2board就是如此，一个软件使用逻辑应该是这样才对。
问题3在新部署上得以解决，验证并没有太大的问题。
![Z_@@G%$K E HGI5F6K~WMDB](https://user-images.githubusercontent.com/55527553/149729467-57c0a7a5-127f-448b-b20f-7b887777ac18.png)
![0~NB9{FMX4%Y~P94_NHJ(TG](https://user-images.githubusercontent.com/55527553/149729673-2b8445e4-f317-40c8-8708-67db00cb942a.png)

该图就滑动的页面，并非自适应。移动端和pc端均是如此。
感谢BoB的回复！

**Comment by GZ1903** [comment]
在1.5.4和1.5.5上进行的测试。结果一致

**Comment by BobCoderS9** [comment]
问题一：测试服前后端都是v1.5.4版本
Demo站：https://v2board.bobv.me/#/login
测试账号：test@qq.com
测试密码：12345678
问题二：我说了每个人想法不一样，你觉得必须点击才能注册，但是我觉得没必要
问题四：你说的是登录页面，现在又截图注册页面，你让我怎么回答。注册页面开启的验证那么多，当然会往下拉，你可以自己修改css适配即可。

**Comment by GZ1903** [comment]
根据你提供的Demo站试了一下，并无任何问题，可以更新一下该主题的包嘛，我觉得与发布的并不一样哈。

**Comment by BobCoderS9** [comment]
demo站跟githup是同步的，先上的demo站测试过后再发的githup包

**Comment by GZ1903** [comment]
我查看了文件差异，发现包是一样的，不知为何却点击不会跳转，我和我的小伙伴亦是如此。。。感谢Bob的回复，问题我自己找找，这个主题可以修加进我的一键脚本嘛，具体是这样的https://github.com/GZ1903/v2board_install。如有不适可以马上进行修改。
![image](https://user-images.githubusercontent.com/55527553/149739132-ca0c4a4f-db19-4e01-8210-3b647d28e32e.png)

**Comment by GZ1903** [comment]
可以了，但是基于1.5.3。正准备更新1.5.4。
![image](https://user-images.githubusercontent.com/55527553/149741275-018df8fa-6d1a-447e-81b6-23a7de2e3c6e.png)

**Comment by GZ1903** [comment]
现在的主题兼容1.5.5嘛，dev分支。

**Comment by BobCoderS9** [comment]
@GZ1903 暂时不考虑兼容dev版本，没时间一直去改

**Comment by GZ1903** [comment]
Hello，Bob。方便将demo站点打包与我嘛，我只想对比一下哪里的差异导致点击不跳转。

**Comment by BobCoderS9** [comment]
@GZ1903 TG上私聊我即可
