### ISSUE TITLE
安装后，出现以前错误 ParseError syntax error, unexpected '0' (T_LNUMBER), expecting variable (T_VARIABLE) or '{' or '$' 

### ISSUE THREAD

**Issue by sunteta** [BobCoderS9/Bob-Theme-Argon#58]
安装后，出现以前错误 ParseError syntax error, unexpected '0' (T_LNUMBER), expecting variable (T_VARIABLE) or '{' or '$'

**Comment by BobCoderS9** [comment]
@sunteta 提问之前多看多想，想想是不是自己的原因。不要碰到错误就跑来问
