### ISSUE TITLE
Bug: 用户后台-节点列表中，状态灯不随节点状态变化而变化

### ISSUE THREAD

**Issue by hhhkkk520** [BobCoderS9/Bob-Theme-Argon#67]
版本1.5.5，主题源码为最新

描述：用户后台的节点列表中，如果某台服务器的服务端处于关闭状态，服务器名前的状态灯依旧显示为绿色。如果切换为v2board原主题，关闭的服务器状态灯为红色。

预期状态：当某台服务器处于宕机、关闭等不正常状态，用户后台节点列表的该台服务器的状态灯应为红色

复现过程：打开节点列表后，所有服务器名前都为绿色状态灯，此时关闭某台服务器的服务端，等待五分钟刷新节点列表页，关闭的服务器名前的状态灯依旧显示为绿色

**Comment by BobCoderS9** [comment]
该问题没测试出来
