### ISSUE TITLE
目前主题的一些问题

### ISSUE THREAD

**Issue by 1665169869** [BobCoderS9/Bob-Theme-Argon#7]
1. 流量显示问题
1.5.2版本流量统计只会统计上行流量，并不会统计下行已用流量
2. 公告问题
公告不会换行了，这是一个比较难受的问题
3. 不显示emoji表情，希望可以增加支持
4. 永久订阅的显示bug
会显示
xx订阅
于 false 到期，距离到期还有 -18839 天， 日后重置流量

**Comment by 1665169869** [comment]
5.选择记住我选项后还是需要登录的bug
比如选择记住我后登录跳转到https://xxxx.xxx/#/dashboard
但如果直接访问域名还是需要登录，不会进行跳转

**Comment by 1665169869** [comment]
6. 工单无法回复，包括管理方跟用户方 不知道是v2b的bug还是主题的bug

**Comment by BobCoderS9** [comment]
已修复
