### ISSUE TITLE
刚刚看到的一个bug

### ISSUE THREAD

**Issue by NMSLSE** [BobCoderS9/Bob-Theme-Argon#74]
可以跳过订单支付，直接开通套餐，来源：
https://www.ahhhhfs.com/28530/

**Comment by BobCoderS9** [comment]
但凡你去搜下v2b代码就知道没有这个接口，而主题是不会修改接口的，要么是机场主自己炒作的，那么就是他自己魔改了后台回调接口被抓包了。（但是被抓包的可能性太小，谁会没事去测试接口呢）

**Comment by NMSLSE** [comment]
呜呜，上了affman和机场主的当了🥲
