### ISSUE TITLE
v1.7.0/v1.7.2/v1.7.3 版本的前端主题

### ISSUE THREAD

**Issue by LLLLFu** [BobCoderS9/Bob-Theme-Argon#82]
下载到theme目录过后要修改当前文件夹名为Bob-Theme-Argon，然后在后台选择主题 【Bob-Theme-Argon】 就行

按文档已经下载，但是后台选择主题的时候，并没有这个主题显示。

**Comment by XiaoDongWang-DiDi** [comment]
同样的问题。后台改了名字，依然无法看到主题。

**Comment by aldington-david** [comment]
> 下载到theme目录过后要修改当前文件夹名为Bob-Theme-Argon，然后在后台选择主题 【Bob-Theme-Argon】 就行
> 
> 按文档已经下载，但是后台选择主题的时候，并没有这个主题显示。

问一下解决了吗

**Comment by mogan1999** [comment]
没有呢，暂时放弃了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月20日(周六) 凌晨2:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BobCoderS9/Bob-Theme-Argon] v1.7.0/v1.7.2/v1.7.3 版本的前端主题 (Issue #82)




  
下载到theme目录过后要修改当前文件夹名为Bob-Theme-Argon，然后在后台选择主题 【Bob-Theme-Argon】 就行
 
按文档已经下载，但是后台选择主题的时候，并没有这个主题显示。
  
问一下解决了吗

**Comment by aldington-david** [comment]
...发现了，是v2board更新后版本不对

**Comment by X-Firefly** [comment]
今天下载了1.73发现也是用不了
