### ISSUE TITLE
公告栏bug

### ISSUE THREAD

**Issue by linger040831** [BobCoderS9/Bob-Theme-Argon#84]
![image](https://github.com/BobCoderS9/Bob-Theme-Argon/assets/84896599/231762b4-7863-4499-977f-8f74bbf20818)
这个card image cap是什么问题啊？
这是我的bug嘛，重装过几次好像都是这样 1.7.3 1.7.4都有这个问题。

**Comment by LLLLFu** [comment]
发布公告，有一栏是图片URL
你留白就会显示card image cap

**Comment by taotao1058** [comment]
我是右上角的用户头像显示不出来，请问是什么原因呀？大佬们

**Comment by linger040831** [comment]
应该是邮箱账号的头像出不来，感觉要弄一个默认头像，不然网络环境不行的话邮箱账号的头像就出不来。
